### ISSUE TITLE
Individual player editing

### ISSUE THREAD

**Issue by Webatron11** [Webatron11/poker#18]
Add the ability to edit a player's balance for the latest session.

**Comment by Xavier-Waters** [comment]
Currently working on this, should help with #8 and eventually #9

**Comment by Xavier-Waters** [comment]
will also help with #19 if we choose to go for that instead of #8

**Comment by Webatron11** [comment]
please do not work on this

**Comment by Xavier-Waters** [comment]
Resolved by #20
