### ISSUE TITLE
Discord bot instead of web ui???

### ISSUE THREAD

**Issue by Webatron11** [Webatron11/poker#19]
A discord bot might be cleaner than a web ui and probably less effort. It would allow for easy notifications as well, because discord.

**Comment by Xavier-Waters** [comment]
:skull: that's going to be fucked but we can probably make it work

**Comment by Xavier-Waters** [comment]
I spent 5+ hours working on this with minimal results, it is certainly not plug and play

**Comment by Xavier-Waters** [comment]
Resolved by #23
